version: '3.4'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5008:8080"
  client:
    image: client
    ports:
      - "3000:5333"
    build:
        context: ../client
        dockerfile: Dockerfile
  proxy:
      image: nginx:mainline
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
      - "5010:5010"